### PR TITLE
Added 404 page with redirect to home button

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
#1

### CODE REVIEW

**Comment by ujwalkumar1995** [comment]
Hey @RajatBhaskare7 @ankurg132 
Did you folks get time to review this PR? Do you have anything that you want me to change in this?

**Comment by RajatBhaskare7** [comment]
@ujwalkumar1995 Try to improve the UI of the page and make something in GDSC Theme

**Comment by ujwalkumar1995** [comment]
@RajatBhaskare7 
Do you have some design in mind?
May be a figma?

**Comment by ujwalkumar1995** [comment]
Hey @RajatBhaskare7 
Have made some changes. Please review.
Designing is not my strong suit when it comes to UI. Would appreciate if there is some design that you can suggest that I can refer to.

**Pull request merged**
